### ISSUE TITLE
[Edit] Needs fallback for unreliable HTML5 Geolocation API

### ISSUE THREAD

**Issue by mxmason** [rockchalkwushock/Bro2Brew_App#1]
Tested on Safari for macOS 9.3.x, as well as Firefox for macOS:
- On the macOS browsers, the user is asked for location permissions, but the map never appears.

There are no errors in the consoles on these browsers. It might have something to do with the way different browsers use the Geolocation API but I'm not certain.

**Edit**: This is definitely an issue with the way OS X gets Geolocaton data. See [this Stack discussion](http://stackoverflow.com/a/6852029). Consider adding error handling so the user will know if the HTML5 Geolocation API has failed them (see [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Geolocation/getCurrentPosition) about error-handling callbacks). For full coverage in later production apps, [polyfills](https://github.com/onury/geolocator) exist. Let's hope that Apple improves the way macOS collects geolocation data in the future!

**Comment by rockchalkwushock** [comment]
Created a fallback to get user's IP address and use lat/lng data from JSON if geolocation is not present in the user's browser. Tested code by itself as a callback as soon as the DOM is loaded and it worked fine. Tried to disable geolocation in Safari & Chrome but never could get it to disable and go to this code. User is just prompted to either use or not use geolocation services and if the choose not too then the Autocomplete method from Google's Places Library is utilized.

``````
function geolocate() {
    if (navigator.geolocation) {
        navigator.geolocation.getCurrentPosition(showPositionByGeo);
    } else {
      console.log('geolocate failed');
      userIP();
    }
}

function userIP()
{
  $.getJSON('https://ipapi.co/json/', function(json_data){
    var data = json_data;
    showPositionByIP(data);
  });
}

function showPositionByIP(position) {
    console.log(position);
    // The Lat & Long values are obtained via the HTML 5 API.
    var latitude = position.latitude;
    var longitude = position.longitude;

    // Creates a new object for using Lat & Long values with Google Map.
    var latLng = new google.maps.LatLng(latitude, longitude);

    // Calls function.
    showMap(latLng);
    // Calls function.
    addNearbyPlaces(latLng);
}```
``````
